# Generated by Django 5.2 on 2025-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable or disable the traffic offense checker. Only admin users can modify this.')),
            ],
            options={
                'verbose_name': 'Checker Configuration',
                'verbose_name_plural': 'Checker Configurations',
            },
        ),
    ]
