# Generated by Django 5.2 on 2025-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_balance_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='check_interval',
            field=models.PositiveIntegerField(default=43200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
