# Generated by Django 5.2 on 2025-09-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_vehicle_check_interval_vehicle_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
    ]
