# Generated by Django 5.2 on 2025-09-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_vehicle_make_remove_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficoffense',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
